service: service

app: crawler
org: adrianopbraga1

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

functions:
  app:   
    handler: handler.list
    events:
      - http:
          path: products
          method: get