service: service

app: api
org: adrianopbraga1

provider:
  name: aws
  runtime: nodejs12.x

  stage: simple-crawler-api
  region: us-east-1

functions:
  app:   
    handler: handler.server
    events:
      - http:
          path: products
          method: get