plugins:
  - serverless-openapi-documentation
  
service: service

app: crawler
org: adrianopbraga1

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

functions:
  app:   
    handler: handler.list
    events:
      - http:
          path: products
          method: get

custom:
  documentation:
    version: 1.0.0
    title: Magazine Luiza Crawler
    description: Seek for products 
    models:
      # GET
      - name: ListProducts
        description: List Products
        contentType: application/json
        schema:
          $schema: http://json-schema.org/draft-04/schema#
          title : Products
          type : array
          items:
            type: object
            properties:
              nome:
                type: string
              preco:
                type: number
              imagem:
                type: string
              estoque:
                type: integer